export const REPORT_BROKEN = 'REPORT_BROKEN';
export const REPORT_FIXED = 'REPORT_FIXED';
export const FETCHING_ESCALATORS = 'FETCHING_ESCALATORS';
export const ERROR_FETCHING_ESCALATORS = 'ERROR_FETCHING_ESCALATORS';
export const SET_ESCALATORS = 'SET_ESCALATORS';

export const SET_ESCALATOR_HISTORY = 'SET_ESCALATOR_HISTORY';
export const FETCHING_ESCALATOR_HISTORY = 'FETCHING_ESCALATOR_HISTORY';
export const ERROR_FETCHING_ESCALATOR_HISTORY = 'ERROR_FETCHING_ESCALATOR_HISTORY';

export const SET_USER_ID = 'SET_USER_ID';

export const SAVING_REPORT = 'SAVING_REPORT';
export const SAVED_REPORT = 'SAVED_REPORT';
export const ERROR_SAVING_REPORT = 'ERROR_SAVING_REPORT';
