export const REPORT_BROKEN = 'REPORT_BROKEN';
export const REPORT_FIXED = 'REPORT_FIXED';
export const TOGGLE = 'TOGGLE';
export const FETCHING_ESCALATORS = 'FETCHING_ESCALATORS';
export const SET_ESCALATORS = 'SET_ESCALATORS';
